### ISSUE TITLE
Makefile missing seperators

### ISSUE THREAD

**Issue by Thomasvdh92** [michaelklishin/tls-gen#14]
Hello, I am trying to use your product to generate files coming from the RabbitMQ tls documentation. I cloned the repository and am now trying to run the "make PASSWORD=bunnies", however I get the error "missing seperator. Stop". It's a common error that gets thrown when using spaces instead of tabs, however I can't figure out why I get this error on your product, since I changed nothing to the makefile. I even removed and recloned the repository, but I'm still getting the same error.

**Comment by lukebakken** [comment]
I am going to close this issue. To use `tls-gen` on Windows, I strongly suggest using `msys2`.

If someone can provide reliable instructions to reproduce this issue I will consider re-opening it. Information should include exact steps to install software and commands to run to reproduce.

**Comment by nperera-medicity** [comment]
I got it to work by copying the top level Makefile into the basic directory and running make PASSWORD=bunnies. System is Linux Subsystem on Windows.(Ubuntu)
