### ISSUE TITLE
Makefile:1: *** missing separator with MYSYS2

### ISSUE THREAD

**Issue by msbasanth** [michaelklishin/tls-gen#15]
Hi,

I am trying o generate certificates in Windows 10 using MYSYS2. 
I am getting error,

```
ic002275@md1uu1ec MSYS /d/tls-gen-master/basic
#make PASSWORD=bunnies

Makefile:1: *** missing separator.  Stop.
```

How to solve this missing separator in Windows 10?

Regards
Basanth

**Comment by lukebakken** [comment]
This is due to the fact that [`Makefile`](https://github.com/michaelklishin/tls-gen/blob/master/basic/Makefile) is a symbolic link to the file in the parent directory. If you copy the parent directory's `Makefile` into the `basic` directory this issue should be fixed.
