### ISSUE TITLE
Showing ERR_CERT_INVALID in browser with Angular 7 client connecting to RabbitMQ

### ISSUE THREAD

**Issue by msbasanth** [michaelklishin/tls-gen#16]
Hi,

I generated a CA and uses it to produce two certificate/key pairs using tls-gen. Then tested generated certificates using openssl tools given @https://www.rabbitmq.com/troubleshooting-ssl.html#openssl-tools.

I could see s_server and s_client connection is fine. **_Verify return code: 0 (ok)_**

I imported these 3 certificates to 'Personal' and 'Trusted Root Certification Authorities' sections.

Then I tried connecting to my TLS enabled RabittMQ server from an Angular client. I used https://github.com/stomp-js/ng2-stompjs-angular7 with **_wss://127.0.0.1:15673/ws_**.

`ng serve --ssl true --ssl-cert D:\sprint43\tls-gen-master\result\client_certificate.pem --ssl-key D:\sprint43\tls-gen-master\result\client_key.pem`

I am getting certificate invalid error. When open and check the certificate I could see "This certificate is ok'.
![certificate_status](https://user-images.githubusercontent.com/17777813/57443136-0ad04800-726b-11e9-92d7-6306408735f7.PNG)

In firefox I am getting a different error.

`An error occurred during a connection to localhost:4200. Certificate type not approved for application. Error code: SEC_ERROR_INADEQUATE_CERT_TYPE `

**Environment:**

- Windows 10 Machine
- RabbitMQ: 3.7.14
- Erlang: 21.3
- Angular 7

Regards
Basanth

**Comment by michaelklishin** [comment]
`SEC_ERROR_INADEQUATE_CERT_TYPE` means that certificate's extended usage [does not fit the task at hand](https://stackoverflow.com/questions/47965359/curl-60-certificate-type-not-approved-for-application-where-wget-works). You are running `ng` (I assume that's a server) with a client certificate, so Chrome rejects it. At least that's my best guess based on what Google reveals for `SEC_ERROR_INADEQUATE_CERT_TYPE`.

Note that you can edit OpenSSL's config file to add any other extended key usage values you need. It is not necessary most of the time, though.
