### ISSUE TITLE
SEC_ERROR_REUSED_ISSUER_AND_SERIAL in Firefox with server certificate created using tls-gen

### ISSUE THREAD

**Issue by msbasanth** [michaelklishin/tls-gen#17]
Hi,

I wanted to connect to RabbitMQ server from an Angular application running in my iPad.

I changed the RabbitMQ broker URL to _wss://<hostname>:15673/ws_ so that we are not referring to loop back ip. 

But with this I am not able to connect to RabbitMQ server. I am connecting from the same machine.

How can connect to RabbitMQ server by providing the server IP address/hostname?

I am getting an error in the client SEC_ERROR_REUSED_ISSUER_AND_SERIAL with Firefox (as attached).
When I checked the server certificate that I created using tls-gen I could see serial number as '01', it looks like gets conflicted with some other certificate with the same serial number.
How can I generate a certificate with unique serial number using tls-gen?

Thanks
Basanth

**Comment by lukebakken** [comment]
Hello! There is no evidence that this is a `tls-gen` issue. I am responding to your message on [`rabbitmq-users`](https://groups.google.com/d/topic/rabbitmq-users/0OdxD1zApLI/discussion) so please continue discussion there.
