### ISSUE TITLE
Gen additional Client Certs

### ISSUE THREAD

**Issue by nolech** [michaelklishin/tls-gen#18]
I didn't see in the documentation how to generate another client cert after the CA and server cert were already created. Is this possible?

**Comment by lukebakken** [comment]
This isn't currently supported, but is possible. Basically the existing data would have to be preserved. We'd be happy to review a pull request that implements this feature.

**Comment by pawel-marciniak** [comment]
Can anyone provide some help on that?

**Comment by lukebakken** [comment]
@nolech @pawel-marciniak please test my branch here:

https://github.com/lukebakken/tls-gen/tree/lrb-gen-client-cert-only

In the `basic` profile, you can use the following command to create additional client certs using a specific common name:

```
make CN=client-name-2 gen-client
```

Look for the files in `result/`, they will have CN as part of the name.

**Comment by pawel-marciniak** [comment]
@lukebakken Great, thanks a lot :) I will definitely give it a try today.

**Comment by tasoss** [comment]
Hello.
I suppose this hasn't been implemented yet.Right?
Is it still ok to use the given solution?

**Comment by lukebakken** [comment]
I'm waiting for someone else to test the changes I made on the `lrb-gen-client-cert-only` branch.

**Comment by mihaj** [comment]
Hi @lukebakken I can test the changes, can you create a PR? It looks like your repo is not available.

**Comment by lukebakken** [comment]
@mihaj you're in luck. I managed to find a clone with the branch. See #31. It needs to have conflicts resolved which I don't have time to do today.

**Comment by mihaj** [comment]
Cool, let me check If I can resolve that.
