### ISSUE TITLE
Error generating basic cert after recent CRL change/PR

### ISSUE THREAD

**Issue by ryanoasis** [michaelklishin/tls-gen#20]
With the latest changes in `master` there is now an issue creating openssl certs because of changes in the `openss.cnf` file.

running: `cd basic && make`

errors:
`Error Loading extension section client_extensions`
...
`Error Loading extension section server_extensions`

I believe it is the 2 lines containing `@crlDistributionPoints = URI:CRL@` under server_extensions and client_extensions sections.

This seems to have been introduced in #19

**Comment by lukebakken** [comment]
Could you please let us know what version of OpenSSL you're using and on what operating system?

@ptusch - care to chime in?

I did not run the changes in #19 on many different systems.

**Comment by lukebakken** [comment]
Thanks for the report @ryanoasis . I reverted #19 in bf4dbd4f77af1a53358bfeb203ab5ba4a406ec1a.

The change in #19 failed using this version of OpenSSL:

```
$ openssl version
OpenSSL 1.1.1d-freebsd  10 Sep 2019
```

@ptusch - please re-test your pull request and re-submit. Thanks.

**Comment by ryanoasis** [comment]
Thanks @lukebakken 

Sure the initial issue was in our Docker container (Alpine Linux v3.10)

Had issues in:

`Alpine Linux v3.10 - OpenSSL 1.1.1d  10 Sep 2019`
and
`macOS - LibreSSL 2.6.5`
