### ISSUE TITLE
Error running make PASSWORD='pass'

### ISSUE THREAD

**Issue by kamel-rush** [michaelklishin/tls-gen#25]
Hi,

I am getting this error when running on windows: Makefile:1: *** missing separator. Stop

**Comment by lukebakken** [comment]
Please double check that you are using GNU Make.

**Comment by kamel-rush** [comment]
I am using Gnu make

**Comment by lukebakken** [comment]
This repository uses a symbolic link from `basic/Makefile` to `Makefile`. This is not supported on Windows. You should copy the top-level `Makefile` to the sub-directory you are using.

**Comment by kamel-rush** [comment]
OK, that made it bypass that problem, but I got this now: 
python3 profile.py regenerate --password "bunnies" \
--common-name UUSSO1LT0278524 \
--client-alt-name UUSSO1LT0278524 \
--server-alt-name UUSSO1LT0278524 \
--days-of-validity 3650 \
--key-bits 2048
process_begin: CreateProcess(NULL, python3 profile.py regenerate --password bunnies --common-name UUSSO1LT0278524 --client-alt-name UUSSO1LT0278524 --server-alt-name UUSSO1LT0278524 --days-of-validity 3650 --key-bits 2048, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:60: regen] Error 2

**Comment by lukebakken** [comment]
Do you have `openssl.exe` in your `PATH`?

**Comment by kamel-rush** [comment]
Yes.

**Comment by lukebakken** [comment]
Is `python3` in your `PATH` as well? Can you run this command on its own?

```
python3 profile.py regenerate --password "bunnies"
--common-name UUSSO1LT0278524
--client-alt-name UUSSO1LT0278524
--server-alt-name UUSSO1LT0278524
--days-of-validity 3650
--key-bits 2048
```

**Comment by kamel-rush** [comment]
I think it worked! The account I was using did not have python3 in the env. variables. Thanks!
