### ISSUE TITLE
Is there a way to generate certificates for multiple subdomains/domains

### ISSUE THREAD

**Issue by oltarasenko** [michaelklishin/tls-gen#26]
I am trying to generate a certificate using the: `make CN=127.0.0.1` command. It works fine with the localhost.

However, I also need to have a certificate in my docker-compose network (which has several domains like: one.node.com, two.node.com, etc)

I am trying to make the certificate pairs valid on all of them, however, nothing seems to work for me. E.g. I was trying to do:
`make CN="one.node.com, two.node.com"` and `make CN="*.node.com"`, however in all cases it was not possible to use certificates, as hostname check failed in all cases :(.

**Comment by michaelklishin** [comment]
A certificate can only have one Common Name (which has long been deprecated) but multiple Subject Alternative Names. `tls-gen` sets up two or three of those (`localhost`, the provided CN value plus the detected hostname). They [come from `openssl.cnf`](https://github.com/michaelklishin/tls-gen/blob/master/basic/openssl.cnf#L77).
