### ISSUE TITLE
make PASSWORD=bunnies error

### ISSUE THREAD

**Issue by ZukkyBaig** [michaelklishin/tls-gen#3]
Hi,

I've installed Python 3.6, latest Make and have openssl installed. I have navigated to the /basics/ folder and ran "make PASSWORD=bunnies" and it responds with:

"python3 profile.py regenerate --password bunnies --common-name DESKTOP-M5MGB2F -V 3650
process_begin: CreateProcess(NULL, python3 profile.py regenerate --password bunnies --common-name DESKTOP-M5MGB2F -V 365
0, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [regen] Error 2"

What am I doing wrong?

**Comment by michaelklishin** [comment]
Can you post the entire shell transcript?

**Comment by ZukkyBaig** [comment]
PS C:\dev\tls-gen\tls-gen> cd .\basic\
PS C:\dev\tls-gen\tls-gen\basic> dir

Directory: C:\dev\tls-gen\tls-gen\basic

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/04/2017     20:17            991 Makefile
-a----       11/04/2017     20:17           1314 openssl.cnf
-a----       11/04/2017     20:17           2208 profile.py
-a----       11/04/2017     20:17           1456 README.md


PS C:\dev\tls-gen\tls-gen\basic> make PASSWORD=bunnies
python3 profile.py regenerate --password bunnies --common-name DESKTOP-M5MGB2F -V 3650
process_begin: CreateProcess(NULL, python3 profile.py regenerate --password bunnies --common-name DESKTOP-M5MGB2F -V 365
0, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [regen] Error 2
PS C:\dev\tls-gen\tls-gen\basic>

**Comment by ZukkyBaig** [comment]
to access python, the env var to access it via powershell is "py" does this need to be changed?

**Comment by michaelklishin** [comment]
Python is expected to be available as `python3`, which is standard naming on Linux and OS X. I have never tried using tls-gen on Windows. The easiest way to do that in case you run into any further issues would be by using [msys2](http://www.msys2.org/).

**Comment by venkatrv** [comment]
I am getting same FileNotFoundError: [WinError 2] The system cannot find the file specified
I am using this tool on windows.
Anyone successful in running this tool on Windows?

**Comment by lukebakken** [comment]
@venkatrv is the `openssl.exe` command in your `PATH`?

**Comment by venkatrv** [comment]
Thanks for quick response.
Yes, but I found that issue is with opensslconf location. It is fixed now and working fine.
