### ISSUE TITLE
SAN support

### ISSUE THREAD

**Issue by srinarayanant** [michaelklishin/tls-gen#4]
Hello ,
Is there a way to include SAN IP address in the generated certificates

**Comment by michaelklishin** [comment]
You can modify OpenSSL configs to include `subjectAltName`. Specifying it on the command line [seems to be quite hacky](https://github.com/openssl/openssl/issues/3311) and ultimately involves a custom config file anyway.

I'm all for people tweaking openssl.cnf and tls-gen code to their specific needs.
